In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import scipy
from scipy.stats import norm
from scipy import stats
from statsmodels.stats.proportion import proportions_ztest
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multicomp import MultiComparison

In [5]:
USprisons = pd.read_csv("New/USDATA/prisonstatsUS/p21stat01.csv")

In [80]:
len(USprisons)

75

In [6]:
USprisons.head()

,Bureau of Justice Statistics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Filename: p21stat01.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Appendix Table 1. Prisoners under the jurisdic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Report title: Prisoners in 2021 – Statistical ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Data source: Bureau of Justice Statistics, Fed...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Author: E. Ann Carson, PhD, BJS Statistician",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
USprisons.drop([0,1,2,3,4,5,6,7,8,11,62,63,64,65,66,67,68,69,70,71,72,73,74], inplace = True)

In [12]:
USprisons.drop('Bureau of Justice Statistics',axis=1, inplace=True)

In [13]:
USprisons

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
9,NaN,Total,White/a,Black/a,Hispanic,American Indian/Alaska Native/a,Asian/a,Native Hawaiian/Other Pacific Islander/a,Two or more races/a,Other/a,Unknown,Did not report
10,NaN,"157,314","47,460","57,225","46,813","3,644","2,170",~,~,~,~,2
12,Alabama,"25,032","11,470","13,353",0,3,4,0,0,202,~,0
13,Alaska,"4,639","1,895",465,125,"1,855",158,95,0,0,46,0
14,Arizona,"33,914","12,960","5,087","13,131","1,880",157,~,~,612,28,59
15,Arkansas,"17,022","9,547","6,771",563,49,48,19,0,23,2,0
16,California,"101,441","20,137","28,710","45,999","1,161","1,162",321,~,"3,951",0,0
17,Colorado,"15,865","6,520","2,769","4,722",542,184,10,~,"1,025",11,82
18,Connecticut,"9,889","2,778","4,208","2,824",34,43,0,0,0,2,0
19,Delaware,"4,810","1,551","2,952",299,1,6,0,0,0,1,0
20,Florida,"80,417","31,599","38,266","10,174",88,18,7,/,262,3,0
21,Georgia,"47,010","17,159","27,715","1,945",22,157,0,0,~,12,0
22,Hawaii,"4,102",915,185,98,21,699,"1,800",145,0,239,0
23,Idaho/d,"8,907","6,419",258,"1,288",329,43,/,/,107,268,195
24,Illinois,"28,475","8,849","15,204","3,671",42,104,/,55,/,45,505
25,Indiana,"24,716","14,292","7,547",992,50,55,9,153,/,38,"1,580"
26,Iowa/e,"8,562","5,492","2,173",605,195,~,~,~,96,1,0
27,Kansas,"8,521","4,781","2,335","1,118",201,75,0,0,5,6,0
28,Kentucky/e,"18,560","14,102","3,879",296,18,~,~,220,30,15,0
29,Louisiana,"26,074","8,863","17,097",66,21,25,0,0,2,~,0
30,Maine,"1,577","1,261",175,~,43,7,1,29,~,61,0
31,Maryland/f,"15,134","3,414","10,730",713,76,49,16,/,114,22,0
32,Massachusetts/g,"6,148","2,561","1,792","1,567",36,102,0,~,~,90,0
33,Michigan,"32,186","13,746","16,278",632,287,94,7,"1,104",0,38,0
34,Minnesota,"8,003","3,732","2,834",471,756,197,/,/,/,13,0
35,Mississippi,"17,332","6,419","10,649",181,35,39,0,0,0,9,0
36,Missouri,"23,422","14,606","7,843",494,97,61,0,/,/,36,285
37,Montana/e,"4,313","3,000",116,133,"1,049",~,~,~,15,0,0
38,Nebraska,"5,600","2,829","1,551",824,287,44,4,/,58,3,0
39,Nevada,"10,202","3,730","3,100","2,764",233,206,113,0,0,56,0
40,New Hampshire,"2,127","1,752",152,125,11,6,1,~,45,35,0
41,New Jersey,"12,506","2,771","7,662","1,941",13,97,0,/,0,22,0
42,New Mexico/h,"5,154","1,385",380,"3,194",455,12,22,0,0,49,0
43,New York,"30,338","7,056","14,930","7,290",289,190,/,/,435,148,0
44,North Carolina,"28,995","11,776","14,620","1,725",576,94,~,~,~,204,0
45,North Dakota,"1,689",982,181,99,418,6,3,0,0,~,0
46,Ohio,"45,029","22,368","19,305","1,156",83,72,/,/,446,/,"1,599"
47,Oklahoma,"22,391","11,109","6,087","1,871","2,099",88,31,~,50,18,"1,038"
48,Oregon,"13,198","9,566","1,236","1,757",411,183,36,/,0,9,0
49,Pennsylvania/f,"37,194","16,427","17,125","3,333",37,114,~,0,0,158,0
50,"Rhode Island/d,f","2,238",887,643,614,21,30,/,/,39,4,0
51,South Carolina/i,"15,759","5,894","9,285",427,25,22,0,/,104,2,0
52,South Dakota/i,"3,353","1,730",262,134,"1,189",26,2,~,10,0,0
53,Tennessee,"21,995","12,047","9,295",560,36,57,/,/,/,/,0
54,Texas,"133,772","45,229","43,485","44,284",63,522,0,0,189,0,0
55,Utah,"5,907","3,487",450,"1,219",333,58,136,0,0,224,0
56,Vermont,"1,287","1,104",124,0,25,8,2,0,9,15,0
57,Virginia/c,"30,357","12,863","16,326",988,32,124,0,0,0,24,0
58,Washington,"13,674","7,555","2,419","2,286",682,590,/,/,56,86,0
59,West Virginia,"5,847","4,956",797,43,5,4,1,41,0,0,0
60,Wisconsin,"20,202","8,947","8,200","1,918",886,244,0,0,/,7,0
61,Wyoming,"2,123","1,593",101,248,159,9,5,0,3,5,0

In [85]:
USprisonscrime = pd.read_csv("New/USDATA/prisonstatsUS/p21stt18.csv")

In [86]:
USprisonscrime.drop([0,1,2,3,4,5,6,7,8,9,11,60,61,62,63,64,65,66], inplace = True)

In [87]:
USprisonscrime.rename(columns={"Bureau of Justice Statistics":"Jurisdiction","Unnamed: 1":"sentencedprisonersincustody",
                               "Unnamed: 2":"Total","Unnamed: 3":"NaN","Unnamed: 4":"Violent","Unnamed: 5":"NaN",
                               "Unnamed: 6":"Property","Unnamed: 7":"NaN","Unnamed: 8":"Drug","Unnamed: 9":"NaN",
                               "Unnamed: 10":"Publicorder","Unnamed: 11":"NaN","Unnamed: 12":"unspecified","Unnamed: 13":"NaN"},inplace=True)

In [88]:
USprisonscrime.drop(['NaN'], axis=1)

,Jurisdiction,sentencedprisonersincustody,Total,Violent,Property,Drug,Publicorder,unspecified
10,Alabama,"21,837",100,59.6,17,14.1,8.1,1.3
12,Arizona/c,"40,753",100,43.8,20.8,23.1,12,0.2
13,Arkansas,"14,078",100,55.6,13.2,19.9,8.3,2.9
14,California,"96,110",100,84.3,7.3,2.1,6,0.3
15,Colorado,"16,175",100,63.6,16.6,7.1,12.6,0.2
16,Connecticut/b,"5,720",100,55.4,10.3,7.3,18.3,8.7
17,Delaware/b,"2,798",100,51.1,6.9,10.3,31.2,0.5
18,Florida,"79,416",100,60.9,18.3,11.2,9.1,0.4
19,Georgia,"46,932",100,69.1,12.5,9.7,8.1,0.7
20,Hawaii/b,"2,097",100,52.7,25,9.6,12.6,0.1
21,Idaho,"8,334",100,28.7,22.1,31.7,17.2,0.3
22,Illinois,"29,341",100,65.2,10.2,10.5,14.1,0.1
23,Indiana,"26,987",100,45.4,14.6,25.1,12.5,2.4
24,Iowa,"8,751",100,35.4,19.1,15.9,12.5,17.1
25,Kansas,"8,615",100,62.9,7.7,23.1,6.2,0.1
26,Kentucky,"18,647",100,43.7,19.7,24.3,11.9,0.4
27,Louisiana,"26,890",100,57.9,13.1,13.6,14.7,0.7
28,Maine,"1,676",100,54,15,22.6,5.5,2.9
29,Maryland,"15,073",100,74.7,8.9,8.5,7.2,0.7
30,Massachusetts,"7,199",100,71.9,5.9,14.6,6.8,0.8
31,Michigan/c,"39,670",100,61.1,15.8,9.5,13.2,0.3
32,Minnesota,"7,752",100,56.6,8.1,17.1,18.1,0.2
33,Mississippi,"17,243",100,57,18.9,16.6,6.5,1.1
34,Missouri,"23,139",100,60.7,16.1,15.3,7.7,0.2
35,Montana,"2,426",100,66.6,12.6,10.3,10.4,0.1
36,Nebraska,"4,976",100,54.1,13.2,15.8,16,1
37,Nevada,"11,128",100,47,16,7.1,28,1.9
38,New Hampshire,"2,215",100,55.1,15.9,15.6,10,3.4
39,New Jersey/c,"22,057",100,50.8,8.2,14.9,8.4,17.7
40,New Mexico/d,"7,086",100,53.4,20.1,16.2,10.1,0.2
41,New York,"34,054",100,60.2,13.9,12.1,13.2,0.6
42,North Carolina,"29,614",100,53.5,11.7,13.4,21.3,0.1
43,North Dakota,"1,504",100,53.8,13.4,24.2,8.1,0.5
44,Ohio,"44,607",100,59.3,13.3,14.7,11.5,1.2
45,Oklahoma,"21,631",100,60.6,16.5,13,9.5,0.4
46,Oregon,"12,803",100,70,15.4,6.9,6.8,0.9
47,Pennsylvania,"39,837",100,62.9,11.8,11.1,12.5,1.7
48,Rhode Island/b,"1,410",100,70.4,9.6,9.9,9.1,1.1
49,South Carolina,"16,259",100,60.3,19,16.5,3.6,0.7
50,South Dakota,"3,160",100,49.4,14.5,27.3,6.7,2.2
51,Tennessee,"27,507",100,51.1,19,20.6,6.8,2.5
52,Texas,"119,056",100,65.7,10.8,13.2,10.3,#
53,Utah,"5,379",100,63.6,15.1,12.1,9.1,0.1
54,Vermont/b,963,100,63.8,16.8,5.6,13,0.8
55,Virginia,"31,001",100,61.2,16.6,15.3,4.2,2.7
56,Washington,"15,121",100,62.1,15.5,6.8,15,0.6
57,West Virginia,"6,009",100,49.8,22.1,10.1,14.4,3.7
58,Wisconsin,"20,123",100,60.8,12.2,12.9,13.9,0.2
59,Wyoming,"2,096",100,55.6,14.6,21.7,7.4,0.8

In [3]:
USprisonageMale = pd.read_csv("New/USDATA/prisonstatsUS/p21stf04.csv")

In [4]:
USprisonageMale

,Bureau of Justice Statistics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Filename: p21stf04.csv,NaN,NaN,NaN,NaN,NaN
1,Figure 4. Imprisonment rates of male U.S. resi...,NaN,NaN,NaN,NaN,NaN
2,Report title: Prisoners in 2021 – Statistical ...,NaN,NaN,NaN,NaN,NaN
3,"Data source: Bureau of Justice Statistics, Fed...",NaN,NaN,NaN,NaN,NaN
4,"Author: E. Ann Carson, PhD, BJS Statistician",NaN,NaN,NaN,NaN,NaN
5,Refer questions to: askbjs@usdoj.gov 202-307-0765,NaN,NaN,NaN,NaN,NaN
6,Date of version: 12/20/2022,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN
8,Figure 4. Imprisonment rates of male U.S. resi...,NaN,NaN,NaN,NaN,NaN
9,NaN,"Rate per 100,000",NaN,NaN,NaN,NaN
10,Age at yearend,White/a,Black/a,Hispanic,American Indian/Alaskan Native,"Asian/a,b"
11,18–19,33,381,84,169,13
12,20–24,247,"1,985",725,"1,181",113
13,25–29,531,"3,379","1,541","2,330",243
14,30–34,714,"3,692","1,793","2,978",259
15,35–39,780,"3,831","1,774","3,370",292
16,40–44,731,"3,693","1,643","3,058",271
17,45–49,607,"3,035","1,347","2,440",245
18,50–54,483,"2,413","1,051","1,928",202
19,55–59,392,"1,946",869,"1,460",146
20,60–64,253,"1,328",657,907,108
21,65 or older,101,488,317,453,43
22,Note: Jurisdiction refers to the legal authori...,NaN,NaN,NaN,NaN,NaN
23,"a/Excludes persons of Hispanic origin (e.g., “...",NaN,NaN,NaN,NaN,NaN
24,"b/Includes Asians, Native Hawaiians, and Other...",NaN,NaN,NaN,NaN,NaN
25,"Source: Bureau of Justice Statistics, Federal ...",NaN,NaN,NaN,NaN,NaN

In [8]:
USprisonageMale.rename(columns={"Bureau of Justice Statistics":"Age at yearend","Unnamed: 1":"White/a",
                               "Unnamed: 2":"Black/a","Unnamed: 3":"Hispanic","Unnamed: 4":"American Indian/Alaskan Native","Unnamed: 5":"Asian/a,b"},inplace=True)

In [9]:
USprisonageMale.drop([0,1,2,3,4,5,6,7,8,9,10,22,23,24,25], inplace = True)

KeyError: '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 22, 23, 24, 25] not found in axis'

### Figure 4. Imprisonment rates of male U.S. residents, based on sentenced prisoners under the jurisdiction of state or federal correctional authorities, by demographic characteristics, December 31, 2021

In [10]:
USprisonage

,Age at yearend,White/a,Black/a,Hispanic,American Indian/Alaskan Native,"Asian/a,b"
11,18–19,33,381,84,169,13
12,20–24,247,"1,985",725,"1,181",113
13,25–29,531,"3,379","1,541","2,330",243
14,30–34,714,"3,692","1,793","2,978",259
15,35–39,780,"3,831","1,774","3,370",292
16,40–44,731,"3,693","1,643","3,058",271
17,45–49,607,"3,035","1,347","2,440",245
18,50–54,483,"2,413","1,051","1,928",202
19,55–59,392,"1,946",869,"1,460",146
20,60–64,253,"1,328",657,907,108
21,65 or older,101,488,317,453,43

In [ ]:
USprisonageFe = pd.read_csv("New/USDATA/prisonstatsUS/p21stf05.csv")

In [ ]:
USprisonageFe.rename(columns={"Bureau of Justice Statistics":"Age at yearend","Unnamed: 1":"White/a",
                               "Unnamed: 2":"Black/a","Unnamed: 3":"Hispanic","Unnamed: 4":"American Indian/Alaskan Native","Unnamed: 5":"Asian/a,b"},inplace=True)

In [6]:
USprisonageFe.drop([0,1,2,3,4,5,6,7,8,9,10,22,23,24,25], inplace=True)